[package]
name = "discovery_server"
version = "0.1.0"
edition = "2018"

[dependencies]
actix = "0.12.0"
actix-web = "3.3.2"
blockchain = { path="../blockchain"}
serde = { version = "1.0.127", features = ["derive"] }
serde_json = "1.0.66"