[package]
name = "node"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "3.3.2"
serde_derive = "1.0.126"
serde = { version = "1.0.127", features = ["derive"] }

[dev-dependencies]
actix-rt = "2.2.0"