[package]
name = "consensus"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "1.11.0", features = ["rt-multi-thread", "macros"]}
futures = "0.3.16"
rust-crypto = "0.2.36"
blockchain = { path = "../blockchain"}
serde_json = "1.0.66"
chrono = "0.4.19"
tracing = "0.1"